### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bo0tzz** [Electron100/butane#262]
The latest release is from over a year ago, but it seems like quite a bit of work has happened since then. Would it be possible to cut a new version?

**Comment by Electron100** [comment]
Yes! I will do that this week.

**Comment by Electron100** [comment]
Published to crates.io yesterday and release notes added to Github today. Above PR documents the breaking changes in the README (should have done that before tagging 0.7, but better late than never)

**Comment by bo0tzz** [comment]
Thanks!
