### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by jayvdb** [Electron100/butane#27]
Most databases support JSON natively, and if they dont butane can convert `serde_json::Value` to and from a Text type on the transparently.

**Comment by jayvdb** [comment]
@Electron100 , I have stubbed out an implementation for his at https://github.com/jayvdb/butane/tree/json .  If this is roughly how you expect it would be done, I will continue with it as time allows.

**Comment by Electron100** [comment]
Thanks! This looks great. Two minor suggestions
1. This should probably be an optional feature similar to Chrono and Uuid support.
2. The value in SqlValRef should be a reference

**Comment by jayvdb** [comment]
@Electron100 I think I have basic support for JSON working with both pg and sqlite at https://github.com/Electron100/butane/pull/38 , with some tests.
