### ISSUE TITLE
rust-analyzer unable to parse query! macro, reports "Unsupported filter expression"

### ISSUE THREAD

**Issue by michael-dm** [Electron100/butane#272]
I'm encountering an issue where rust-analyzer is unable to correctly parse the `query!` macro from Butane. Here's a minimal example of the problematic code:

```rust
query!(Profile, name == "Hello")
```

This results in the following error from rust-analyzer:

```
rust-analyzer: Unsupported filter expression '(name == "Hello")'
```

Additional debug info:
```
Expr::Paren { attrs: [], paren_token: Paren, expr: Expr::Binary { attrs: [], left: Expr::Path { attrs: [], qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident { ident: "name", span: SpanData { range: 297..301, anchor: SpanAnchor(FileId(16777220), 5), ctx: SyntaxContextId(0) } }, arguments: PathArguments::None }] } }, op: BinOp::Eq(EqEq), right: Expr::Lit { attrs: [], lit: Lit::Str { token: "Hello" } } } }
```

This code compiles and runs correctly, but rust-analyzer is unable to properly analyze it.
Also, this version work with no issue : 
```rust
Profile::query().filter(filter!(Profile, name == "Hello"));
```

Environment:
- Rust version: 1.80.1
- Butane version: 0.7.0
- Zed Editor: 0.152.4

Any assistance in resolving this issue would be greatly appreciated.

**Comment by ugochukwu-850** [comment]
It's common for rust analyzer to have some issues with macros .

Have you considered restarting the server . 

Or reopening Vscode. That's should help reindex stuff .

**Comment by RobertoMaurizzi** [comment]
I've been having the same issue since the first time I used `quey!` or ~find!`... 🤔 
I'm on Linux Debian: @Electron100 what OS are you using?
Do you have any pointer for me to try to investigate this?
If not I'll try to `cargo expand` a simple project to see if I can understand what;s the issue.

**Comment by RobertoMaurizzi** [comment]
... and of course in the simple project it doesn't misbehave 😅 
It's probably getting tricked by the fact the project has both a library and a binary I have an unrelated project in Bevy with multiple binaries where I often get false positives from rust-analyzer because it's checking both binaries at the same time.
It'll try to see what happens if I pass it a `check.target` value.

**Comment by Electron100** [comment]
> I'm on Linux Debian: @Electron100 what OS are you using?

I'm primarily on Arch Linux at home, though I also have Windows systems (and work from Windows for $dayjob).

I'm afraid I'm still skeptical there's anything that can be done from the Butane end, but if somebody can give me steps that lead to a consistent repro, I'm happy to reopen this and investigate more.
