### ISSUE TITLE
Possible to port it to Python?

### ISSUE THREAD

**Issue by mh-firouzjah** [Electron100/butane#274]
hello there!
I'm not a rust developer but I have used python/django and I really like Django ORM but it has some issues which till now it doesn't support async very well and it becomes a problem for Django.
on the other hand sqla is something different and it has some bugs, due to its huge codebase those are not simple to be fixed.
tldr;
as if these days people are making python packages like pydantic, ruff and ... using rust. Is there any chance that your package could be used directly in python code?
I mean could it become an ORM package for python?

**Comment by Electron100** [comment]
Hi @mh-firouzjah . I don't think so, unfortunately. Butane is in part inspired by the Django ORM but makes very heavy use of Rust macros and of strong typing. Much of the work happens at _compile_ time. The concepts don't map well to Python. I think making a Python wrapper around Butane would be hard and probably non-pythonic. You'd likely end up needing to have the Python code generate rust code and invoke the Rust toolchain as a build step, and then give up the runtime safety that's the raison d'etre of Butane. Possibly cleverer minds than mine see a path, but it's not straightforward.

**Comment by mh-firouzjah** [comment]
thank you for your time. I will search for a solution and maybe do some rust 😉

**Comment by RobertoMaurizzi** [comment]
Just as a sidenote, I started putting together an application using Leptos and Butane and it feels quite a bit like Django, minus maybe my lack of knowledge and everything being still very very beta (a bit like in the days of Django 0.9x ;-) )
