### ISSUE TITLE
Unexpected error during makemigration [butane 3.0]

### ISSUE THREAD

**Issue by ieow** [Electron100/butane#4]
I encounter the error below when trying to makemigration with butane 3.0
Encountered unexpected error: (De)serialization error unknown variant `KnownId`, expected `Known` or `Deferred` at line 1 column 62

It works fine when I downgrade back to 2.1

To recreate :
use butane  3.0
butane makemigration init

**Comment by Electron100** [comment]
@ieow did you upgrade butane_cli to 0.3 as well? If you were using butane=0.3 as your library dependency, but running 0.2.1 of the butane cli, that could cause this error.

**Comment by ieow** [comment]
Yes, I didnt upgraded butane_cli v0.3.0
I upgraded it and it works fine now!
Thanks
