### ISSUE TITLE
Set columm as unique

### ISSUE THREAD

**Issue by ieow** [Electron100/butane#5]
How to se the column as unique?
Is there a field such as #[unique] (as same as #[pk]) to define the column as unique data?

**Comment by Electron100** [comment]
At the moment, the only way to set a unique constraint on a column would be to manually edit the migration sql after it's generated. 
It should be fairly straightforward to add a #[unique] field attribute though. Let me see if I can take a stab at that tonight.

**Comment by ieow** [comment]
Thanks for the workaround!
Thanks also for considering to implement #[unique] feature !!

**Comment by Electron100** [comment]
Took a couple days before I found the time I'm afraid, but I've just published 0.3.1 with #[unique]. Let me know if you see any issues!

**Comment by Electron100** [comment]
Closing, as this is implemented in 0.3.1 and I haven't heard any feedback. Feel free to reopen if you see issues.

**Comment by ieow** [comment]
Just tried it with 0.3.1. It works great!
