### ISSUE TITLE
Funding?

### ISSUE THREAD

**Issue by LoveIsGrief** [Electron100/butane#75]
Hi,

Sorry to create an issue, but the discussions aren't activated.

Yours' seems like the only rust ORM that wants to go the django ORM route and spare devs the pain of carefully crafting SQL queries + migrations to let us focus on writing logic. In my opinion an endeavor worth tipping.

Would you be willing to setup an account on https://liberapay.com/ to receive donations per bank transfer? That's where I can tip, but others would probably be more willing to tip on github, patreon, [linux foundation](https://lfx.linuxfoundation.org/tools/crowdfunding) or others.

Of course if you don't want donations, then I'll just leave you with a "Thank you for your efforts! They are much appreciated" :slightly_smiling_face: 

Cheers

**Comment by Electron100** [comment]
Hi, thank you for the kind words! While I won't rule out setting up donations in the future, for the moment I'm going to respectfully decline them. There's a couple reasons
1. I have a very comfortable software engineering day job (unrelated to Rust or databases) so it's probably better for folks to spend their discretionary tipping funds on projects which really need the funds.
2. While I hope to make this project as useful as possible, it's purely a hobby project from my perspective. I prefer to keep money out of my hobbies to avoid any risk of them becoming obligations. Especially at the moment as I've been unable to give this Butane the time it deserves the last few months.

I do appreciate the thought though!

**Comment by LoveIsGrief** [comment]
> I prefer to keep money out of my hobbies to avoid any risk of them becoming obligations

I understand. Even without money some people don't understand it's a hobby.

Well then, thanks for answering and for the work you've already put into this. Have fun!
