### ISSUE TITLE
GitHub tag missing

### ISSUE THREAD

**Issue by jayvdb** [Electron100/butane#88]
https://github.com/Electron100/butane/releases is missing 0.6.0

**Comment by Electron100** [comment]
Arrg, sorry. Fixed
https://github.com/Electron100/butane/releases

**Comment by jayvdb** [comment]
Any chance you are interested in adding butane to https://github.com/rust-lang/this-week-in-rust "call for participants"? e.g. https://this-week-in-rust.org/blog/2023/05/17/this-week-in-rust-495/#call-for-participation

If so, see https://users.rust-lang.org/t/twir-call-for-participation/4821

We'd need to pick one issue to request help on.
